server:
  port: ${PORT:8080}
spring:
  application:
    name: pharmacy-app
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/pharmacy-app?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Adem147852369..}
  jpa:
    show-sql: false
  jackson:
    time-zone: GMT+1
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    secret: ${JWT_SECRET:PharmaSeekAppSecretKey2026VeryLongKey}
    accessTokenValidity: 7200000
    refreshTokenValidity: 604800000
    secureCookie: false
    sameSite: Lax
cors:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
